[23기 박종규] 카카오 소셜로그인, 로그인 데코레이터, Test 코드
wecode-bootcamp-korea/23-2nd-BeerBnB-backend pull request #4
Opened 2021-08-19 12:33 UTC by dwenpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 카카오 소셜로그인, 로그인 데코레이터, Test 코드
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 카카오 소셜 로그인 뷰 작성
- 로그인 데코레이터 작성
- Test 코드 작성(성공, 실패, 예외)
- 
## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-20 02:02 UTC, lordmyshepherd requested changes

2021-08-20 02:02 UTC, lordmyshepherd commented on users/tests.py
> +		)
인덴트 맞춰주세요!

2021-08-20 02:02 UTC, lordmyshepherd commented on users/tests.py
> +				}
마찬가지로 인덴트 맞춰주세요~

2021-08-20 02:02 UTC, lordmyshepherd commented on users/tests.py
> +				}
인덴트 맞춰주세요~

2021-08-20 02:02 UTC, lordmyshepherd commented on users/utils.py
> +	return wrapper
인덴트 4칸으로 맞춰주세요. 기존에 merge된 모든 코드들이 indent 4로 맞춰져 있기 때문에, 팀 양식에 맞춰주세요~

```suggestion
def login_decorator(func):
    def wrapper(self, request, *args, **kwargs):
        try:
	    token   = request.headers.get("Authorization")
	    payload = jwt.decode(token, SECRET_KEY, algorithms = "HS256")

	    if not User.objects.filter(id = payload.get("id")).exists() :
	        return JsonResponse({"message" : "INVALID_MEMBER"}, status = 404)

            user = User.objects.get(id = payload["id"])
	    request.user = user

        except jwt.exceptions.DecodeError:
	    return JsonResponse({"message" : "INVALID_TOKEN"}, status = 403)

	return func(self, request, *args, **kwargs)

    return wrapper
```

2021-08-20 02:02 UTC, lordmyshepherd commented on users/utils.py
> +	return wrapper
추가로 데코레이터에서 `positional arguments`와 `keyword args`를 사용하시는 이유가 있으신가요?

2021-08-20 02:02 UTC, lordmyshepherd commented on users/utils.py
> +	return wrapper
status 코드도 정확하게 반환해주세요!

2021-08-20 02:02 UTC, lordmyshepherd commented on users/views.py
> +
마찬가지로 인덴트 맞춰주세요~

2021-08-20 02:02 UTC, lordmyshepherd commented on users/views.py
> +			)
여기서는 두가지 피드백을 드릴 수 있을 것 같습니다.
1. 변수를 선언했을 때는 해당 변수에 담기는 값이 무엇인지 명확하게 작성할 것.
```suggestion
response = requests.get(
    "https://kapi.kakao.com/v2/user/me", 
    headers = {"Authorization" : f"Bearer {access_token}"}
)
```
2. requests 모듈을 사용할 때에는 반드시 `timeout` option을 걸어 주셔야합니다. 그렇지 않으면 요청을 보낸 서버로부터 응답이 올때까지 무기한 기다리는 문제가 발생하게 됩니다.

2021-08-20 02:02 UTC, lordmyshepherd commented on users/views.py
> +				return JsonResponse({"message" : "NO_PROFILE_IN_KAKAO"}, status = 404)
보통 이렇게 `third party 서버`의 응답의 성공/실패 여부를 판단할때에는 `status 코드로 비교`해야 명확하고 디버깅하기 쉽습니다.

```suggestion
```

2021-08-20 02:02 UTC, lordmyshepherd commented on users/views.py
> +			user.save()
여기서는 `get_or_create()` method를 사용해보시면, 더욱 가독성 좋은 코드를 작성하실 수 있을 것 같습니다.
추가로 인덴트 4로 맞춰주세요.

2021-08-20 02:59 UTC, dwenpark commented on users/views.py
> +			user.save()
병민님, 피드백 감사합니다. ger_or_create도 고민했었는데 유저가 로그인하고, 카카오 정보가 업데이트된 상태에서
다시 로그인 했을때, 유저 정보를 업데이트 해주어야할 것 같아서 위와 같은 로직으로 구성해봤습니다.
그리고 제 환경에서 인덴트 4로 보입니다 ㅠㅠ..

2021-08-20 06:39 UTC, dwenpark commented
컨벤션 수정했습니다!!

2021-08-22 11:56 UTC, lordmyshepherd approved these changes

2021-08-22 11:56 UTC, lordmyshepherd commented on users/views.py
> +            user.save()
이 부분은 실제로 소셜로그인을 구현할때는 고민해보시면 좋겠어요~
"과연 실제로 매번 로그인할때마다 업데이트를 해줘야되는가"

2021-08-22 11:56 UTC, lordmyshepherd commented
LGTM 👍

2021-08-22 11:56 UTC, merged

2021-08-22 12:14 UTC, dwenpark commented on users/views.py
> +            user.save()
주말에도 감사합니다.. 병민님
말씀주신 내용 고려해보겠습니다!