[23기 김도담] Add : 호스트 등록 API 작성
wecode-bootcamp-korea/23-2nd-BeerBnB-backend pull request #6
Opened 2021-08-20 14:41 UTC by damdream

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)

- 호스트 등록 API를 작성하였습니다.
-  기본 요소인 숙소이름, 인원, 가격이 0일 경우 에러를 반환합니다.
- 최대 입실인원은 4명으로 제한했습니다.
- 이미지 미업로드 및 주소 미입력시 에러를 반환합니다.
- user의 is_host 값이 false면 True로 값을 업데이트 해줍니다.
- 유닛테스트 완료했습니다.......

![스크린샷 2021-08-23 오후 9 39 40](https://user-images.githubusercontent.com/81546305/130474322-79ac3fbf-0dfb-4ceb-9876-9374023ad66f.png)

 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 02:01 UTC, lordmyshepherd requested changes

2021-08-23 02:01 UTC, lordmyshepherd commented on products/urls.py
> +    path('', HostEnrollment.as_view()),
`POST /host` http method와 URI만으로 해당 데이터에 대한 엑션을 파악할 수 있기 때문에 Enrollment라는 용어는 삭제해도 될 것 같습니다. 그리고 나중에 host 정보를 받아오는 get()를 구현해야될 때, HostEnrollment Class 안에 get method로 구현해야 되기 때문에 아래 class명도 `Class Host`로 수정해주세요~

```suggestion
    path('', Host.as_view()),
```

2021-08-23 02:01 UTC, lordmyshepherd commented on products/views.py
> +        print(request)
프린트문은 지워주세요~

2021-08-23 02:01 UTC, lordmyshepherd commented on products/views.py
> +    #@login_decorator
로그인 데코레이터 코드가 merge 되었으므로 리베이스 하신 후에 열어주시면 될 것 같네요~

2021-08-23 02:01 UTC, lordmyshepherd commented on products/views.py
> +            Image.objects.create(product = product, image = data["image"])
여기 코드는 좀 이상해보이네요?
`data["image_id"]`와`data["image"]`에 담겨지는 값은 어떤 형태인가요??

2021-08-23 02:01 UTC, lordmyshepherd commented on products/views.py
> +
`addressSplit = data["product.address"].split(" ")[0]`을 직접 선언하지 않고, 아래와 같이 사용하는게 좋을 것 같네요~
왜 그럴까요??

```suggestion
        Category.objects.create(
            product       = product,
            big_address   = data["product.address"].split(" ")[0],
            small_address = data["product.address"].split(" ")[1],
        )
        
```

2021-08-23 02:01 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({"MESSAGE": "ADDRESS_DOES_NOT_EXISTS" },status = 400)
여기는 어떤 목적으로 작성하신 코드인가요?

2021-08-23 02:54 UTC, damdream commented on products/urls.py
> +    path('', HostEnrollment.as_view()),
네 수정하겠습니다~

2021-08-23 02:55 UTC, damdream commented on products/views.py
> +        print(request)
네 수정했습니다!

2021-08-23 02:55 UTC, damdream commented on products/views.py
> +    #@login_decorator
네 열었습니다!

2021-08-23 02:57 UTC, damdream commented on products/views.py
> +            return JsonResponse({"MESSAGE": "ADDRESS_DOES_NOT_EXISTS" },status = 400)
이미지나 주소가 존재하지 않는 경우 에러를 반환하기 위함입니다! host 등록시 해당 정보가 필수 값인데, 등록 이후 에러를 검증해야해서 에러 검증 코드를 아래로 뺐습니다!

2021-08-23 02:58 UTC, damdream commented on products/views.py
> +
변수를 선언하지 않고 코드 안에서 해결하는 것이 더욱 간결하고, 코드를 통일된 방식으로 작성할 수 있기 때문인 듯 합니다..!

2021-08-23 03:07 UTC, damdream commented on products/views.py
> +            Image.objects.create(product = product, image = data["image"])
해당 데이터 통일했습니다! json 형태로 받아온 이미지 데이터를 for문을 통해 image_id에 넣기 위한 구문입니다..!

2021-08-24 12:40 UTC, lordmyshepherd approved these changes

2021-08-24 12:41 UTC, lordmyshepherd commented
LGTM 👍

2021-08-24 12:41 UTC, merged