[23기 박종규] Add: 상품 리스트 검색 기능 구현
wecode-bootcamp-korea/23-2nd-BeerBnB-backend pull request #7
Opened 2021-08-23 04:48 UTC by dwenpark

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 주소 검색
- 날짜 검색
- 인원 검색
- 테스트 코드 작성
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 주소 검색 
파라미터를 안받을 경우 모든 숙소

- 날짜 검색 [필수 파라미터]
1. 원하는 체크인 날짜가 숙소 예약기간(체크인-체크아웃)에 겹쳐있는지 확인하고 제외
2. 예약된 숙소의 체크인이 유저가 원하는 예약기간에 겹쳐있는지 확인하고 제외
(체크인 = 폐구간, 체크아웃 = 개구간)

- 가능 인원 검색
파라미터로 받아서 수용 가능 인원인지 확인

- 상기 조건을 모두 만족하는 숙소를 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-08-23 08:46 UTC, lordmyshepherd requested changes

2021-08-23 08:46 UTC, lordmyshepherd commented on products/views.py
> +            return JsonResponse({"message" : "VALUE_ERROR"}, status = 400)
아래와 같은 방향으로 코드를 수정하면 좀 더 가독성이 좋아질 것 같은데 어떠신가요? 
1. `count = request.GET.get("count", 1)` 부분에서는 default로 1을 주면 if문이 필요 없을 것 같습니다.
2. `prefetch_related(Prefetch("image_set", to_attr = "to_product_image"))`에서와 같은 경우에는 `prefetch_related("image_set")`와 같이 Prefetch 객체를 사용하지 않아도 됩니다~
호출부에서 의미도 더 명확하구요~ `[product.image for product in product.to_product_image]` vs `[product.image for product in product.image_set.all()]`


```suggestion
            address  = request.GET.get("address")
            count = request.GET.get("count", 1)
            checkin  = request.GET.get("checkin")
            checkout = request.GET.get("checkout")
            
            q1 = Q()
            q2 = Q()
            
            if address:
                q1 &= Q(address__contains=address)
                
            if checkin and checkout:
                new_checkout = datetime.strptime(checkout, "%Y-%m-%d").date() - timedelta(1)
                q2 = (Q(booking__check_out__gt = checkin) & Q(booking__check_in__lte = checkin)) | Q(booking__check_in__range = [checkin, new_checkout])
                
            products = Product.objects.filter(q1, head_count__gte = count).exclude(q2).prefetch_related("image_set")
                        
            results = [{
                "id"        : product.id,
                "name"      : product.name,
                "count"     : product.head_count,
                "latitude"  : product.latitude,
                "longitude" : product.longitude,
                "price"     : product.price,
                "image"     : [product.image for product in product.image_set.all()]
            } for product in products]
            
            return JsonResponse({"message" : products}, status = 200)
        
        except KeyError:
            return JsonResponse({"message" : "KEY_ERROR"}, status = 400)
        
        except ValueError:
            return JsonResponse({"message" : "VALUE_ERROR"}, status = 400)
```

2021-08-23 09:44 UTC, dwenpark commented on products/views.py
> +            return JsonResponse({"message" : "VALUE_ERROR"}, status = 400)
피드백 감사합니다 병민님!
해당 사항 반영해서 다시 푸쉬했습니다 :)

2021-08-24 01:15 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-08-24 01:16 UTC, merged